export const TwoFactorErrorCode = {
  ENROLLMENT_BEGIN_FAILED: "ENROLLMENT_BEGIN_FAILED",
  ENROLLMENT_ALREADY_ACTIVE: "ENROLLMENT_ALREADY_ACTIVE",
  ENROLLMENT_CONFIRM_FAILED: "ENROLLMENT_CONFIRM_FAILED",
  NO_PENDING_ENROLLMENT: "NO_PENDING_ENROLLMENT",
  TOTP_INVALID_CODE: "TOTP_INVALID_CODE",
  TOTP_LOCKED_OUT: "TOTP_LOCKED_OUT",
  RECOVERY_CODE_INVALID: "RECOVERY_CODE_INVALID",
  RECOVERY_CODE_LOCKED_OUT: "RECOVERY_CODE_LOCKED_OUT",
  EMAIL_OTP_REQUEST_FAILED: "EMAIL_OTP_REQUEST_FAILED",
  EMAIL_OTP_INVALID: "EMAIL_OTP_INVALID",
  EMAIL_OTP_LOCKED_OUT: "EMAIL_OTP_LOCKED_OUT",
  DISABLE_FAILED: "DISABLE_FAILED",
  QR_RENDER_FAILED: "QR_RENDER_FAILED",
  STATUS_LOAD_FAILED: "STATUS_LOAD_FAILED",
  NETWORK_ERROR: "NETWORK_ERROR",
  UNKNOWN: "UNKNOWN",
} as const;

export type TwoFactorErrorCodeValue =
  (typeof TwoFactorErrorCode)[keyof typeof TwoFactorErrorCode];
