-- Seed for DGII
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000001')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000001', 'Razon Social User0 LastName0', 'Comercial User0 LastName0', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000011')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000011', 'Razon Social User1 LastName1', 'Comercial User1 LastName1', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000021')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000021', 'Razon Social User2 LastName2', 'Comercial User2 LastName2', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000031')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000031', 'Razon Social User3 LastName3', 'Comercial User3 LastName3', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000041')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000041', 'Razon Social User4 LastName4', 'Comercial User4 LastName4', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000051')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000051', 'Razon Social User5 LastName5', 'Comercial User5 LastName5', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000061')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000061', 'Razon Social User6 LastName6', 'Comercial User6 LastName6', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000071')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000071', 'Razon Social User7 LastName7', 'Comercial User7 LastName7', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000081')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000081', 'Razon Social User8 LastName8', 'Comercial User8 LastName8', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000091')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000091', 'Razon Social User9 LastName9', 'Comercial User9 LastName9', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000101')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000101', 'Razon Social User10 LastName10', 'Comercial User10 LastName10', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000111')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000111', 'Razon Social User11 LastName11', 'Comercial User11 LastName11', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000121')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000121', 'Razon Social User12 LastName12', 'Comercial User12 LastName12', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000131')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000131', 'Razon Social User13 LastName13', 'Comercial User13 LastName13', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000141')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000141', 'Razon Social User14 LastName14', 'Comercial User14 LastName14', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000151')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000151', 'Razon Social User15 LastName15', 'Comercial User15 LastName15', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000161')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000161', 'Razon Social User16 LastName16', 'Comercial User16 LastName16', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000171')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000171', 'Razon Social User17 LastName17', 'Comercial User17 LastName17', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000181')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000181', 'Razon Social User18 LastName18', 'Comercial User18 LastName18', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000191')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000191', 'Razon Social User19 LastName19', 'Comercial User19 LastName19', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000201')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000201', 'Razon Social User20 LastName20', 'Comercial User20 LastName20', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000211')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000211', 'Razon Social User21 LastName21', 'Comercial User21 LastName21', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000221')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000221', 'Razon Social User22 LastName22', 'Comercial User22 LastName22', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000231')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000231', 'Razon Social User23 LastName23', 'Comercial User23 LastName23', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000241')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000241', 'Razon Social User24 LastName24', 'Comercial User24 LastName24', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000251')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000251', 'Razon Social User25 LastName25', 'Comercial User25 LastName25', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000261')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000261', 'Razon Social User26 LastName26', 'Comercial User26 LastName26', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000271')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000271', 'Razon Social User27 LastName27', 'Comercial User27 LastName27', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000281')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000281', 'Razon Social User28 LastName28', 'Comercial User28 LastName28', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000291')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000291', 'Razon Social User29 LastName29', 'Comercial User29 LastName29', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000301')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000301', 'Razon Social User30 LastName30', 'Comercial User30 LastName30', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000311')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000311', 'Razon Social User31 LastName31', 'Comercial User31 LastName31', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000321')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000321', 'Razon Social User32 LastName32', 'Comercial User32 LastName32', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000331')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000331', 'Razon Social User33 LastName33', 'Comercial User33 LastName33', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000341')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000341', 'Razon Social User34 LastName34', 'Comercial User34 LastName34', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000351')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000351', 'Razon Social User35 LastName35', 'Comercial User35 LastName35', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000361')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000361', 'Razon Social User36 LastName36', 'Comercial User36 LastName36', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000371')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000371', 'Razon Social User37 LastName37', 'Comercial User37 LastName37', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000381')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000381', 'Razon Social User38 LastName38', 'Comercial User38 LastName38', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000391')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000391', 'Razon Social User39 LastName39', 'Comercial User39 LastName39', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000401')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000401', 'Razon Social User40 LastName40', 'Comercial User40 LastName40', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000411')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000411', 'Razon Social User41 LastName41', 'Comercial User41 LastName41', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000421')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000421', 'Razon Social User42 LastName42', 'Comercial User42 LastName42', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000431')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000431', 'Razon Social User43 LastName43', 'Comercial User43 LastName43', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000441')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000441', 'Razon Social User44 LastName44', 'Comercial User44 LastName44', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000451')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000451', 'Razon Social User45 LastName45', 'Comercial User45 LastName45', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000461')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000461', 'Razon Social User46 LastName46', 'Comercial User46 LastName46', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000471')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000471', 'Razon Social User47 LastName47', 'Comercial User47 LastName47', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000481')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000481', 'Razon Social User48 LastName48', 'Comercial User48 LastName48', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000491')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000491', 'Razon Social User49 LastName49', 'Comercial User49 LastName49', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000501')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000501', 'Razon Social User50 LastName50', 'Comercial User50 LastName50', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000511')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000511', 'Razon Social User51 LastName51', 'Comercial User51 LastName51', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000521')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000521', 'Razon Social User52 LastName52', 'Comercial User52 LastName52', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000531')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000531', 'Razon Social User53 LastName53', 'Comercial User53 LastName53', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000541')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000541', 'Razon Social User54 LastName54', 'Comercial User54 LastName54', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000551')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000551', 'Razon Social User55 LastName55', 'Comercial User55 LastName55', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000561')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000561', 'Razon Social User56 LastName56', 'Comercial User56 LastName56', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000571')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000571', 'Razon Social User57 LastName57', 'Comercial User57 LastName57', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000581')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000581', 'Razon Social User58 LastName58', 'Comercial User58 LastName58', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000591')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000591', 'Razon Social User59 LastName59', 'Comercial User59 LastName59', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000601')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000601', 'Razon Social User60 LastName60', 'Comercial User60 LastName60', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000611')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000611', 'Razon Social User61 LastName61', 'Comercial User61 LastName61', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000621')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000621', 'Razon Social User62 LastName62', 'Comercial User62 LastName62', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000631')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000631', 'Razon Social User63 LastName63', 'Comercial User63 LastName63', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000641')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000641', 'Razon Social User64 LastName64', 'Comercial User64 LastName64', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000651')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000651', 'Razon Social User65 LastName65', 'Comercial User65 LastName65', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000661')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000661', 'Razon Social User66 LastName66', 'Comercial User66 LastName66', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000671')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000671', 'Razon Social User67 LastName67', 'Comercial User67 LastName67', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000681')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000681', 'Razon Social User68 LastName68', 'Comercial User68 LastName68', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000691')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000691', 'Razon Social User69 LastName69', 'Comercial User69 LastName69', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000701')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000701', 'Razon Social User70 LastName70', 'Comercial User70 LastName70', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000711')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000711', 'Razon Social User71 LastName71', 'Comercial User71 LastName71', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000721')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000721', 'Razon Social User72 LastName72', 'Comercial User72 LastName72', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000731')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000731', 'Razon Social User73 LastName73', 'Comercial User73 LastName73', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000741')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000741', 'Razon Social User74 LastName74', 'Comercial User74 LastName74', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000751')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000751', 'Razon Social User75 LastName75', 'Comercial User75 LastName75', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000761')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000761', 'Razon Social User76 LastName76', 'Comercial User76 LastName76', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000771')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000771', 'Razon Social User77 LastName77', 'Comercial User77 LastName77', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000781')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000781', 'Razon Social User78 LastName78', 'Comercial User78 LastName78', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000791')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000791', 'Razon Social User79 LastName79', 'Comercial User79 LastName79', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000801')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000801', 'Razon Social User80 LastName80', 'Comercial User80 LastName80', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000811')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000811', 'Razon Social User81 LastName81', 'Comercial User81 LastName81', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000821')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000821', 'Razon Social User82 LastName82', 'Comercial User82 LastName82', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000831')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000831', 'Razon Social User83 LastName83', 'Comercial User83 LastName83', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000841')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000841', 'Razon Social User84 LastName84', 'Comercial User84 LastName84', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000851')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000851', 'Razon Social User85 LastName85', 'Comercial User85 LastName85', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000861')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000861', 'Razon Social User86 LastName86', 'Comercial User86 LastName86', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000871')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000871', 'Razon Social User87 LastName87', 'Comercial User87 LastName87', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000881')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000881', 'Razon Social User88 LastName88', 'Comercial User88 LastName88', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000891')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000891', 'Razon Social User89 LastName89', 'Comercial User89 LastName89', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000901')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000901', 'Razon Social User90 LastName90', 'Comercial User90 LastName90', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000911')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000911', 'Razon Social User91 LastName91', 'Comercial User91 LastName91', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000921')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000921', 'Razon Social User92 LastName92', 'Comercial User92 LastName92', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000931')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000931', 'Razon Social User93 LastName93', 'Comercial User93 LastName93', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000941')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000941', 'Razon Social User94 LastName94', 'Comercial User94 LastName94', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000951')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000951', 'Razon Social User95 LastName95', 'Comercial User95 LastName95', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000961')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000961', 'Razon Social User96 LastName96', 'Comercial User96 LastName96', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000971')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000971', 'Razon Social User97 LastName97', 'Comercial User97 LastName97', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000981')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000981', 'Razon Social User98 LastName98', 'Comercial User98 LastName98', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200000991')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200000991', 'Razon Social User99 LastName99', 'Comercial User99 LastName99', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001001')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001001', 'Razon Social User100 LastName100', 'Comercial User100 LastName100', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001011')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001011', 'Razon Social User101 LastName101', 'Comercial User101 LastName101', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001021')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001021', 'Razon Social User102 LastName102', 'Comercial User102 LastName102', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001031')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001031', 'Razon Social User103 LastName103', 'Comercial User103 LastName103', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001041')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001041', 'Razon Social User104 LastName104', 'Comercial User104 LastName104', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001051')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001051', 'Razon Social User105 LastName105', 'Comercial User105 LastName105', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001061')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001061', 'Razon Social User106 LastName106', 'Comercial User106 LastName106', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001071')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001071', 'Razon Social User107 LastName107', 'Comercial User107 LastName107', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001081')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001081', 'Razon Social User108 LastName108', 'Comercial User108 LastName108', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001091')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001091', 'Razon Social User109 LastName109', 'Comercial User109 LastName109', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001101')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001101', 'Razon Social User110 LastName110', 'Comercial User110 LastName110', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001111')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001111', 'Razon Social User111 LastName111', 'Comercial User111 LastName111', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001121')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001121', 'Razon Social User112 LastName112', 'Comercial User112 LastName112', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001131')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001131', 'Razon Social User113 LastName113', 'Comercial User113 LastName113', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001141')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001141', 'Razon Social User114 LastName114', 'Comercial User114 LastName114', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001151')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001151', 'Razon Social User115 LastName115', 'Comercial User115 LastName115', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001161')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001161', 'Razon Social User116 LastName116', 'Comercial User116 LastName116', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001171')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001171', 'Razon Social User117 LastName117', 'Comercial User117 LastName117', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001181')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001181', 'Razon Social User118 LastName118', 'Comercial User118 LastName118', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001191')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001191', 'Razon Social User119 LastName119', 'Comercial User119 LastName119', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001201')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001201', 'Razon Social User120 LastName120', 'Comercial User120 LastName120', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001211')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001211', 'Razon Social User121 LastName121', 'Comercial User121 LastName121', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001221')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001221', 'Razon Social User122 LastName122', 'Comercial User122 LastName122', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001231')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001231', 'Razon Social User123 LastName123', 'Comercial User123 LastName123', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001241')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001241', 'Razon Social User124 LastName124', 'Comercial User124 LastName124', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001251')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001251', 'Razon Social User125 LastName125', 'Comercial User125 LastName125', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001261')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001261', 'Razon Social User126 LastName126', 'Comercial User126 LastName126', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001271')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001271', 'Razon Social User127 LastName127', 'Comercial User127 LastName127', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001281')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001281', 'Razon Social User128 LastName128', 'Comercial User128 LastName128', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001291')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001291', 'Razon Social User129 LastName129', 'Comercial User129 LastName129', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001301')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001301', 'Razon Social User130 LastName130', 'Comercial User130 LastName130', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001311')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001311', 'Razon Social User131 LastName131', 'Comercial User131 LastName131', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001321')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001321', 'Razon Social User132 LastName132', 'Comercial User132 LastName132', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001331')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001331', 'Razon Social User133 LastName133', 'Comercial User133 LastName133', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM DGII WHERE Rnc = '40200001341')
INSERT INTO DGII (Rnc, NombreRazonSocial, NombreComercial, Categoria, RegimenPagos, Estado, ActividadEconomica, AdministracionLocal, FacturadorElectronico, LicenciasVhm, FechaModificacion) VALUES ('40200001341', 'Razon Social User134 LastName134', 'Comercial User134 LastName134', 'MIPYME', 'NORMAL', 'ACTIVO', 'SERVICIOS INMOBILIARIOS', 'SAN PEDRO DE MACORIS', 'SI', 'NO', GETUTCDATE());
