<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="C:\Users\Alva\Desktop\Anteproyecto-Verify\src\backend\Application\Application.csproj" />
    <ProjectReference Include="C:\Users\Alva\Desktop\Anteproyecto-Verify\src\backend\Domain\Domain.csproj" />
  </ItemGroup>

</Project>